package exception_handling.labs;

/**
 * Exception Handling Exercise 1:
 *
 *      1) Demonstrate a try/catch.
 *      2) Demonstrate a try/catch with multiple catch statements.
 *      3) Demonstrate a try/catch/finally block.
 *      4) Demonstrate a nested try/catch.
 *      5) Demonstrate how to throw an exception.
 *      6) Demonstrate throwing an exception in one method and catching it in another method.
 *
 */

